[package]
name = "delsum"
version = "0.1.0"
authors = ["8051Enthusiast <8051enthusiast@protonmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
clap = "2"
rayon = "1.1"
bitvec = "0.19"
lazy_static = "1.4"
rand = "0.7"
poly = { path = "poly" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
bigint = "4.4.3"

[workspace]
members = [
    "poly",
]

[lib]
name = "libdelsum"
path = "src/lib.rs"

[[bin]]
name = "delsum"
path = "src/bin.rs"
