[package]
name = "delsum"
version = "0.1.0"
authors = ["8051Enthusiast <8051enthusiast@protonmail.com>"]
edition = "2018"


[lib]
name = "libdelsum"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
rand = "0.7"