package delsum:web;
interface checksums {
  record checksummed-file {
    file: list<u8>,
    checksum: list<u8>,
  }
  record checksum-ranges {
    start: list<s32>,
    end: list<s32>,
  }
  variant checksum-error {
    model(string),
    other(string),
  }

  reverse: func(files: list<checksummed-file>, model: string, trailing-check: bool) -> result<list<string>, checksum-error>;

  part: func(files: list<checksummed-file>, model: string, trailing-check: bool, end-relative: bool) -> result<list<checksum-ranges>, checksum-error>;

  check: func(files: list<u8>, model: string) -> result<string, checksum-error>;
}
world delsum {
  export checksums;
}
