package delsum:web;
interface checksums {
  record checksummed-file {
    file: list<u8>,
    checksum: list<u8>,
  }
  record checksum-ranges {
    start: list<s32>,
    end: list<s32>,
  }

  reverse: func(files: list<checksummed-file>, model: string) -> result<list<string>, string>;

  part: func(files: list<checksummed-file>, model: string) -> result<list<checksum-ranges>, string>;
}
world delsum {
  export checksums;
}
