[package]
name = "delsum-bin"
version = "0.1.0"
authors = ["8051Enthusiast <8051enthusiast@protonmail.com>"]
edition = "2018"

[[bin]]
name = "delsum"
path = "src/bin.rs"

[dependencies]
rayon = "1.1"
clap = "2"
delsum = { path = ".." }
