name: Build Binary
on: [push]
jobs:
  build_windows:
    name: Build Windows Binary
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true
      - uses: msys2/setup-msys2@v2
        with:
          install: gcc make wget lzip m4
      - run: mkdir "$GITHUB_WORKSPACE/output"
      - shell: msys2 {0}
        run: bash build.sh $GITHUB_WORKSPACE/output
      - run: |
        export DELSUM_STATIC_LIBS=1
        export DELSUM_NTL_LIB_PATH="$GITHUB_WORKSPACE/output/lib"
        export DELSUM_NTL_INCLUDE="$GITHUB_WORKSPACE/output/include
        cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: delsum_win
          path: target/x86_64-unknown-linux-gnu/release/delsum.exe
  build_linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt install m4 lzip
      - run: mkdir "$GITHUB_WORKSPACE/output"
      - run: bash build.sh $GITHUB_WORKSPACE/output
      - run: ls
      - run: |
        export DELSUM_STATIC_LIBS=1
        export DELSUM_NTL_LIB_PATH="$GITHUB_WORKSPACE/output/lib"
        export DELSUM_NTL_INCLUDE="$GITHUB_WORKSPACE/output/include
        cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: delsum-linux
          path: target/release/delsum
#  build_macos:
#    name: Build MacOS Binary
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2    
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - run: brew install m4 lzip
#      - run: mkdir output
#      - run: bash build.sh 64
#      - run: ls
#      - run: cargo build --release
#        env:
#          DELSUM_STATIC_LIBS: 1
#          DELSUM_NTL_LIB_PATH: "./output/lib"
#          DELSUM_NTL_INCLUDE: "./output/include"
#      - uses: actions/upload-artifact@v2
#        with:
#          name: delsum-macos
#          path: target/release/delsum
